### ISSUE TITLE
what is the retrieval source for GSM8K?

### ISSUE THREAD

**Issue by Barianc** [CraftJarvis/RAT#3]
Hello, your work has left a deep impression on me. 

It's mentioned in your paper that the codeparrot/github-jupyter dataset are employed as your primary search vector library for code generation and mathematical reasoning tasks. But isn't this dataset only used for the code generation task? So, may I ask what the retrieval knowledge source for GSM8K is? Or is it indeed possible to use codeParrot/gitHub-jupyter for retrieval in the GSM8K task? 

Looking forward to your reply.

**Comment by linhaowei1** [comment]
Hi Barianc,

Actually, we also use code generation as tools to solve mathematical tasks, following the method of PAL (you can check Appendix A.2 for details). The final solution is given by executing the LLM-generated code via a Python interpreter.
